sitemaps:
  - https://www.sellcell.com/sitemap.xml
  - https://www.sellcell.com/blog/sitemap_index.xml

# Regex patterns MUST be in single quotes
allow_patterns:
  - '^https?://www\.sellcell\.com/(sell|trade|trade-in|phones|cell-phones|iphone|samsung|google|google-pixel|pixel|ipad|tablets)/'
  - '^https?://www\.sellcell\.com/blog/.*'

disallow_patterns:
  - '^https?://www\.sellcell\.com/aff/'
  - '^https?://www\.sellcell\.com/aff-widget/'
  - '^https?://www\.sellcell\.com/affiliates/'
  - '^https?://www\.sellcell\.com/buy-go/'
  - '^https?://www\.sellcell\.com/buy-search/'
  - '^https?://www\.sellcell\.com/buy-update/'
  - '^https?://www\.sellcell\.com/canada-go/'
  - '^https?://www\.sellcell\.com/go/'
  - '^https?://www\.sellcell\.com/search/'
  - '^https?://www\.sellcell\.com/update/'
  - '^https?://www\.sellcell\.com/wordpress-'
  - '^https?://www\.sellcell\.com/zz-'

rate_limit_seconds: 1.0
http_timeout: 25

xml_item_xpath: "//item"
xml_name_xpath: "./title"
xml_price_xpath: "./price"

name_normalize: true
currency_prefix: ""
price_increment: 5.0
round_to: 1
