'use client';

import { Disclosure } from '@headlessui/react';
import { ChevronDownIcon } from '@heroicons/react/24/outline';

const faqs = [
  {
    question: 'How are quotes calculated?',
    answer:
      'Quotes are generated by combining live SellCell feeds, partner price sheets, and your internal margins. Admins can override pricing per device or merchant.',
  },
  {
    question: 'Can customers check out as guests?',
    answer:
      'Yes. We store guest orders without a userId and provide a claim flow for customers to attach historical orders to a new account later.',
  },
  {
    question: 'Do you support shipping kits and labels?',
    answer:
      'ShipEngine and ShipStation integrations allow auto-generated kits, reprints, address validation, and void flows accessible from the admin portal.',
  },
];

export function FaqAccordion() {
  return (
    <section className="bg-white py-20">
      <div className="mx-auto max-w-4xl px-6">
        <h2 className="text-3xl font-semibold text-slate-900">Frequently asked questions</h2>
        <dl className="mt-10 space-y-4">
          {faqs.map((faq) => (
            <Disclosure key={faq.question}>
              {({ open }) => (
                <div className="overflow-hidden rounded-xl border border-slate-200">
                  <Disclosure.Button className="flex w-full items-center justify-between px-6 py-4 text-left text-base font-medium text-slate-900">
                    <span>{faq.question}</span>
                    <ChevronDownIcon
                      className={`h-5 w-5 transition-transform ${open ? 'rotate-180 text-brand' : 'text-slate-400'}`}
                    />
                  </Disclosure.Button>
                  <Disclosure.Panel className="border-t border-slate-100 bg-slate-50 px-6 py-4 text-sm text-slate-600">
                    {faq.answer}
                  </Disclosure.Panel>
                </div>
              )}
            </Disclosure>
          ))}
        </dl>
      </div>
    </section>
  );
}
