name: Deploy to Firebase Hosting and Auto-Commit Version

on:
  push:
    branches:
      - main  # Set this to your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust to your project's Node version

      - name: Install Firebase CLI and dependencies
        run: |
          npm install -g firebase-tools
          npm install

      - name: Build project (if needed)
        run: npm run build # Uncomment and modify if your project needs a build step

      - name: Increment version and deploy
        run: |
          # Increment the version number in package.json
          npm version patch --no-git-tag-version

          # Deploy to Firebase using the secret token
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Commit and push the version update
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add package.json
          git commit -m "Auto-version update to v$(node -p "require('./package.json').version")"
          git push